2024-08-28 14:21:13,786 - ERROR - An error occurred: Value error: invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "C:\Users\prali\Desktop\Pralish\Emplyment Work\University Work\Software\SupremeSlicer\supremeslicer\lib\main_engine.py", line 152, in _run_animation
    user_in = int(input("Please choose an option\n"))
ValueError: invalid literal for int() with base 10: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\main.py", line 29, in main
    main_client.cli()
  File "C:\Users\prali\Desktop\Pralish\Emplyment Work\University Work\Software\SupremeSlicer\supremeslicer\lib\main_engine.py", line 226, in cli
    self._run_animation()
  File "C:\Users\prali\Desktop\Pralish\Emplyment Work\University Work\Software\SupremeSlicer\supremeslicer\lib\main_engine.py", line 176, in _run_animation
    raise ValueError(f"Value error: {ve}")
ValueError: Value error: invalid literal for int() with base 10: ''
